spring:
  application:
    name: oauth2-resource-server

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5555/oauth2db
    username: oauth2
    password: oauth2

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/identity

server:
  port: 8090